--- 
 
  gather_facts: false
  hosts: localhost
  name: Create a sandbox instance
  tasks: 
    - name: Launch instance
       
        assign_public_ip: true
        group: "{{ security_group }}"
        image: "{{ image }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ keypair }}"
        region: "{{ region }}"
        vpc_subnet_id: subnet-abdf58cd
        wait: true
      register: ec2
  vars: 
    image: ami-04d29b6f966df1537
    instance_type: t2.micro
    keypair: samfixbreakfix
    region: us-east-1
    security_group: default
    
    
    
