- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: samfixbreakfix
    instance_type: t2.micro
    security_group: default
    image: ami-04d29b6f966df1537 
    region: us-east-1
  tasks:
     - name: Launch instance
       amazon.aws.ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-abdf58cd
         assign_public_ip: yes
      register: ec2
